# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            SKAAE
tagline:          A blog...
url:              http://skaae.github.io/
paginate:         1
baseurl:          /
author:
  name:           Søren Sønderby
  url:            https://skaae.github.com
  email:          skaaesonderby@gmail.com

# header
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'


# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
